### ISSUE TITLE
Remove link to mailchimp archives

### ISSUE THREAD

**Issue by GrumpyOldTroll** [cvuuf/church#100]
Based on conversation with the share team and the spate of fraudulent attempts to impersonate Rev. Nica to solicit gift cards, we think we should probably remove the mailchimp archives (it seems a possibly good candidate for the source list of email addresses that have been attacked).  It might help slightly for the future, though it probably doesn't solve the problem.

**Comment by shaneniebergall** [comment]
@GrumpyOldTroll to be clear, you want this page removed? https://www.chaliceuu.org/blog/news-notes/

What about this one? https://www.chaliceuu.org/blog/newsletter/

**Comment by GrumpyOldTroll** [comment]
Yes, I think removing https://www.chaliceuu.org/blog/news-notes/ is probably right.

I guess probably we should take down https://www.chaliceuu.org/blog/newsletter/ too.  Hard to be sure, but I guess it makes sense.

**Comment by GrumpyOldTroll** [comment]
Got a request from Katie (representing community life) to have the archives findable somewhere, so I think we should probably replace the archives on https://www.chaliceuu.org/blog/news-notes/ (anywhere else?) with a link to the announcements group at https://groups.google.com/a/cvuuf.org/g/announcements.

**Comment by GrumpyOldTroll** [comment]
Discussed this in the council meeting and blessed the idea of removing the archives and providing a public link to the announcements group (and leaving it joinable by/visible to the public).

Updated this page with a link to the announcements group:
https://www.chaliceuu.org/blog/news-notes/

Deleted the old monthly archive page:
https://www.chaliceuu.org/blog/newsletter/
