### ISSUE TITLE
Replace Mailchimp Signup plugin with alternate form

### ISSUE THREAD

**Issue by GrumpyOldTroll** [cvuuf/church#102]
2 places get broken if you deactivate the mailchimp plugin:

 1. https://www.chaliceuu.org/blog/join-mailing-list/

![image](https://user-images.githubusercontent.com/361578/89716606-360c8000-d963-11ea-8ff6-e334036f6776.png)

 2. The bottom of the front page (inside the "Footer 3" widget, where it uses '[mc4wp_form id="2538"]' in a siteorigin box.

![image](https://user-images.githubusercontent.com/361578/89716601-29882780-d963-11ea-92a9-b5dc10dfd42f.png)

These should be replaced with a similar form that results in an invitation to join the announcements google group:

https://groups.google.com/a/cvuuf.org/g/announcements

This form might have to generate an email to somebody, it looks like there's not a plugin that takes care of it?

Community life is requesting that we replace these with something like the contact us form:
https://www.chaliceuu.org/about-us/contact-chalice-uu-fellowship-of-the-conejo-valley/

https://www.chaliceuu.org/about-us/contact-chalice-uu-fellowship-of-the-conejo-valley/

**Comment by shaneniebergall** [comment]
Replaced footer and mailing list page with blurb linking to Breeze form.

https://www.chaliceuu.org/blog/join-mailing-list/
