### ISSUE TITLE
Location page

### ISSUE THREAD

**Issue by kendra-m** [cvuuf/church#105]
Add a temporary note that indicates we are not meeting in the physical building during the Coronavirus pandemic; maybe include info on how to find zoom links for different meetings/events.

https://www.chaliceuu.org/about-us/location/

**Comment by shaneniebergall** [comment]
Great catch, I've updated it with the following:

![image](https://user-images.githubusercontent.com/59004683/96400201-fe9d2980-1184-11eb-8955-1e4525118032.png)

**Comment by kendra-m** [comment]
Thank you for the update, Shane!

Kendra


Kendra D. Mellinger (she/her)
(805) 391-6075
