### ISSUE TITLE
404 Page Not Found

### ISSUE THREAD

**Issue by kendra-m** [cvuuf/church#107]
https://www.chaliceuu.org/about-us/location/accessibility/

**Comment by GrumpyOldTroll** [comment]
Hi Kendra,
Do you know where this link came from?
I searched and found it here, do you know if it came anywhere else also?
https://www.chaliceuu.org/about-us/location-of-chalice-uu-fellowship/

**Comment by GrumpyOldTroll** [comment]
Found another page about website accessibility here:
https://www.chaliceuu.org/website-accessibility/

That's a stub tho, we probably need some new content here.

**Comment by kendra-m** [comment]
Hi Jake,

My memory leaves out things sometimes, but I do not remember working on it.
Was my name on a change made to it?

The language of the text on the website accessibility page leads me to
think the stub was generated by the template or some widget/app in
WordPress?

Kendra D. Mellinger (She/Her <https://www.mypronouns.org/what-and-why>)
Phone & Text: (805) 391-6075

**Comment by GrumpyOldTroll** [comment]
Yes, I think you reported the issue originally.  I was just going thru the issues and I wasn't sure where you might have encountered the dead link from, tho I did find one place.  If you don't have others I'll assume it's just that, and I guess take it out since we don't really have a right page for it. Thanks.

**Comment by GrumpyOldTroll** [comment]
I searched for accessibility and found a few places that mentioned or referenced it:

- https://www.chaliceuu.org/about-us/location-of-chalice-uu-fellowship/accessibility/
- https://www.chaliceuu.org/website-accessibility/
- https://www.chaliceuu.org/visiting-us/
- https://www.chaliceuu.org/about-us/location-of-chalice-uu-fellowship/

I updated the first 2 with some blurbs about our future intent with regard to the website, and fixed the links on the other 2.  Thanks for reporting this.
