### ISSUE TITLE
Need to update signup forms in 2 places

### ISSUE THREAD

**Issue by shaneniebergall** [cvuuf/church#111]
In the site footer, and on https://www.chaliceuu.org/blog/join-mailing-list/ we have a mailchimp form, but we're not using mailchimp anymore.

We need to replace this with our google groups signup.

**Comment by GrumpyOldTroll** [comment]
https://github.com/CVUUFellowship/church/issues/102 is maybe a duplicate of this.

**Comment by GrumpyOldTroll** [comment]
Consensus is to try to find a form for signing up to a google group, namely announcements:
https://groups.google.com/a/cvuuf.org/g/announcements/

Note that the archives should also be replaceable with a link to this group, since it's visible to anyone on the web.

**Comment by shaneniebergall** [comment]
@GrumpyOldTroll The only documentation I can find about embedding a google group form is all super old (example: https://sites.google.com/site/sandorexampleclub/how-to/step-11) and refers to a unique group name, something I don't see anywhere on the settings of the group. Perhaps we just provide a link to signup instead?

Also, although it says the group is public, you can only view info about the group anonymously. You can't view the messages unless you are part of the group. Is that okay, or do we need to change permissions?

![image](https://user-images.githubusercontent.com/59004683/94099204-3d86cc00-fddf-11ea-9321-13f841f2ec81.png)

**Comment by GrumpyOldTroll** [comment]
Thanks @shaneniebergall , I hadn't realized.  I changed the settings.  (It also allowed any members to post until just now, which was lucky it hadn't been abused yet.)

If there's no right way to do a form, maybe we change the form to just have a link and suggest they join?  I think that should work.  I'll send an email to Chavonne, Annie, and Katie to see what they think.

**Comment by shaneniebergall** [comment]
This has been done.

**Comment by GrumpyOldTroll** [comment]
Thanks!
