### ISSUE TITLE
Purpose of "chaliceuu.org/Locations" page

### ISSUE THREAD

**Issue by markgrisez** [cvuuf/church#113]
Unable to find how to navigate to this page from the Website including all sub pages such as chaliceuu.org/locations/cvuuf-sanctuary.  It appears that the location of Chalice is clearly indicated in other areas of the Website.

**Comment by shaneniebergall** [comment]
If this page is not linked to, is this an issue? @GrumpyOldTroll shall we just delete it?

**Comment by GrumpyOldTroll** [comment]
Deleting this seems like it should be fine, I think.

**Comment by shaneniebergall** [comment]
I trashed this page
