### ISSUE TITLE
Links to Facebook need to be updated

### ISSUE THREAD

**Issue by brianpletcher** [cvuuf/church#116]
all references to https://www.facebook.com/CVUUF/ need to be updated to https://www.facebook.com/ChaliceUUF/
like on our home page: "Coronavirus Update
During this time of Coronavirus, the Chalice community will be meeting online and connecting regularly on our Facebook page. Please go to our **Facebook** page if ..."

**Comment by GrumpyOldTroll** [comment]
Thanks Brian, I searched for facebook.com/cvuuf and found 5 pages and 1 published post (plus one draft post), which are all fixed now I believe:

- https://www.chaliceuu.org/blog/coronavirus-info/
- https://www.chaliceuu.org/stay-in-touch/
- https://www.chaliceuu.org/visiting-us/
- https://www.chaliceuu.org/worship/
- https://www.chaliceuu.org/about-us/location-of-chalice-uu-fellowship/
- https://www.chaliceuu.org/coronavirus-update/

Additionally, the [stay in touch](https://www.chaliceuu.org/stay-in-touch/) page had a button that wasn't working, so I updated it with this tool: https://developers.facebook.com/docs/plugins/like-button/, and it should be ok now.  So I think it's fixed.
