### ISSUE TITLE
worship services listed on  web site

### ISSUE THREAD

**Issue by WLubka** [cvuuf/church#24]
Just checking in to ask about the process for updating "This Month's Worship" listed on our web site. It's April 2 and the web site still has the March services. Can we put our heads together this week to determine a reliable process for posting the information in a timely manner?  Thanks everyone!

**Comment by cvuuf** [comment]
Hi Willie,

Dianna and Rev. Anne and I talked about this 2 weeks ago, and it was going
to become part of Dianna's regular weekly duties to update the sermon
postings. I walked through how to do it with her, but perhaps something
else came up last week, or there was a problem getting it working?

Liza called earlier and offered to take care of it, but I agree we need to
get this worked out. Sorry for not being on top of it this week, hopefully
better next time around.

Regards,
Jake

**Comment by cvuuf** [comment]
Thank you Jake!

**Comment by cvuuf** [comment]
Hi...

I can talk with her about it. Or maybe she's on this e-mail? I see two addresses cc'd that I don't recognize: office@cvuuf.org; does that go to her as well as admin@cvuuf.org? And CVUUFellowship/church followed by a very strange group of letters/numbers.

I think we need to understand that Dianna has a lot of brand new information to learn; and every week there's new things that come up, that she knows nothing about. Not surprising, in my experience; it's impossible to train someone on all the details of church life! So she may simply not have been able to get to it yet.

Thanks, Willie, for letting us know. ~ Anne

**Comment by cvuuf** [comment]
Hi all,

Rev Anne, Jake & I did meet about me taking this over this responsibility.
I will make it a priority to update this.  I appreciate your understanding
in my learning process.

Dianna

On Tue, Apr 5, 2016 at 11:20 PM, Anne Hines minister@cvuuf.org wrote:

> Hi...
> 
> I can talk with her about it. Or maybe she's on this e-mail? I see two
> addresses cc'd that I don't recognize: office@cvuuf.org; does that go to
> her as well as admin@cvuuf.org? And CVUUFellowship/church followed by a
> very strange group of letters/numbers.
> 
> I think we need to understand that Dianna has a lot of brand new
> information to learn; and every week there's new things that come up, that
> she knows nothing about. Not surprising, in my experience; it's impossible
> to train someone on all the details of church life! So she may simply not
> have been able to get to it yet.
> 
> Thanks, Willie, for letting us know. ~ Anne
> 
> On Apr 5, 2016, at 3:17 PM, Jake Holland wrote:
> 
> Hi Willie,
> 
> Dianna and Rev. Anne and I talked about this 2 weeks ago, and it was going
> to become part of Dianna's regular weekly duties to update the sermon
> postings. I walked through how to do it with her, but perhaps something
> else came up last week, or there was a problem getting it working?
> 
> Liza called earlier and offered to take care of it, but I agree we need to
> get this worked out. Sorry for not being on top of it this week, hopefully
> better next time around.
> 
> Regards,
> Jake
> 
> On Sat, Apr 2, 2016 at 6:46 AM, WLubka notifications@github.com wrote:
> 
> > Just checking in to ask about the process for updating "This Month's
> > Worship" listed on our web site. It's April 2 and the web site still has
> > the March services. Can we put our heads together this week to determine a
> > reliable process for posting the information in a timely manner? Thanks
> > everyone!
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/CVUUFellowship/church/issues/24
> 
> ## 
> 
> You received this message because you are subscribed to the Google Groups
> "Admin" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to admin+unsubscribe@cvuuf.org.

## 

_Dia__nna Mueller *
*Office Administrator *
*Conejo Valley Unitarian Universalist Fellowship_
