### ISSUE TITLE
contact us page comments

### ISSUE THREAD

**Issue by WLubka** [cvuuf/church#30]
As a web user, I would be much happier when visiting this page ( http://staging.cvuuf.org/about-us/contact/ ) if the phone number, an email address, and a physical mailing address were provided front and center on the page. A submit form is fine to include as well along with the other methods to contact us. My hearts sinks whenever I click a contact us page and find just a submit form.  I feel that they are trying to discourage me from contacting them. Even if the information such as phone and address are available somewhere else in the web site, when I click "Contact Us" I expect contact information to be right there and I do not want to have to search for it.  Also, where it says "To reach our minister or staff members, visit their profiles on our Staff page." - it would be nice if the words "Staff page" were hyperlinked to that page.

**Comment by GrumpyOldTroll** [comment]
Rewrote the text on this page, it no longer refers to the staff page, and includes the info requested. This seems like a great idea.
