### ISSUE TITLE
New Room Request needs renaming

### ISSUE THREAD

**Issue by shaneniebergall** [cvuuf/church#58]
https://www.chaliceuu.org/blog/room-reservations/

says "CVUUF room requests"

**Comment by shaneniebergall** [comment]
@GrumpyOldTroll The change here needs to be made on a Google Form. Do you know who manages this?
https://docs.google.com/forms/d/e/1FAIpQLSdhJiq3S7PWbGCxqWZIONxHsna4ABMzkFFJfbwwJDBeJWOP0g/viewform

**Comment by GrumpyOldTroll** [comment]
Ah, right.  That's mine.  It's changed, thanks for pointing the right spot.
