### ISSUE TITLE
Child Dedications link incorrect

### ISSUE THREAD

**Issue by shaneniebergall** [cvuuf/church#60]
On https://www.chaliceuu.org/worship/what-to-expect-in-worship/
the "Child Dedications" link

Takes you to: http://demo.uuatheme.org/worship/child-dedications/
That's wrong.

**Comment by chuckfernald** [comment]
It seems like the link is to a legitimate one of our pages, but there is no content there.
I removed the link 
<a href="http://demo.uuatheme.org/worship/child-dedications/">child dedications</a>
and just substituted in the word "child dedications" on the page.
