### ISSUE TITLE
Learning Menu / Side Bar reordering

### ISSUE THREAD

**Issue by shaneniebergall** [cvuuf/church#61]
https://www.chaliceuu.org/learning/

The OWL and Church Library drop down menu order doesn't match the left hand navigator

![image](https://user-images.githubusercontent.com/59004683/71652350-b8500a00-2cd9-11ea-8246-6dae09be2c97.png)

**Comment by shaneniebergall** [comment]
I reordered the top menu to match the left sidebar menu.

However, I'm curious where the left sidebar menus are defined. @GrumpyOldTroll , do you know? I ask because there are a few more mismatches between top and left menus (actually almost all of them are off), and some left menus don't even show up (Ex: https://www.chaliceuu.org/visiting-us/)

**Comment by GrumpyOldTroll** [comment]
I think "no menu" comes from not having a parent. I think the left menus are implicitly built from the parent structure, tho I'm not totally sure...

**Comment by kellyniebergall** [comment]
From meeting: Pages have a heirarchy, denoted with -, --, etc. Can be changed with page attributes (parent, order, etc). Shane to play around with this.

**Comment by shaneniebergall** [comment]
Thanks, makes sense now. Closing as the task was done 2 weeks ago
