### ISSUE TITLE
Childspace inaccurate

### ISSUE THREAD

**Issue by shaneniebergall** [cvuuf/church#63]
https://www.chaliceuu.org/learning/children-youth-religious-education/childspace-2/

Our paid Childspace Supervisor is CPR-certified and has worked with small children for a number of years.  Our paid Childspace Worker is a lifelong Conejo Valley Unitarian Universalist member.I don't this is accurate.  This is not our name.

**Comment by chuckfernald** [comment]
reference to lifelong CVUUF member was previously removed.
