### ISSUE TITLE
 Lower/Upper/Middle Elementary updates

### ISSUE THREAD

**Issue by shaneniebergall** [cvuuf/church#64]
https://www.chaliceuu.org/learning/children-youth-religious-education/childspace/
https://www.chaliceuu.org/learning/children-youth-religious-education/upper-elementary/
https://www.chaliceuu.org/learning/children-youth-religious-education/middle-school-youth-2/

All these need fixing on ALL 3 above pages.

1. The age-appropriate curriculum uses story, music and activity to help children enjoy lessons based on the Unitarian Universalist Principles and Sources.  Has a link to http://wp.me/P7pUMk-vj which attempts to resolve to https://staging.cvuuf.org/?page_id=1941

2. If you scroll way down there is a heading for Blog with no content.

3. "Teachers are volunteer Conejo Valley Unitarian Universalist Fellowship members."

**Comment by kellyniebergall** [comment]
Updates made.
