### ISSUE TITLE
YRUU update

### ISSUE THREAD

**Issue by shaneniebergall** [cvuuf/church#65]
https://www.chaliceuu.org/learning/children-youth-religious-education/middle-school-youth/

"The Young Religious Unitarian Universalists program curriculum is youth-driven and discussion-based and acquaints the participant with other Unitarian Universalists beyond the Conejo Valley Unitarian Universalist Fellowship."

"Volunteers from the Conejo Valley Unitarian Universalist Fellowship guide and chaperone the youth in this program."

should be Chalice

**Comment by chuckfernald** [comment]
Changed to 
"Chalice YRUU program". 

the Chalice Fellowship

Volunteers from Chalice guide
