### ISSUE TITLE
Learning - Extras updates

### ISSUE THREAD

**Issue by shaneniebergall** [cvuuf/church#66]
https://www.chaliceuu.org/learning/children-youth-religious-education/extras/

"For more information, please contact Samantha Dickerson, Director of Religious Education."
Another link to Sam that goes to home

"The Conejo Valley Unitarian Universalist Fellowship believes that every age and stage of life is equally valued and equally supported in our worship."

"The Conejo Valley Unitarian Universalist Children’s Choir performs periodically throughout the church year." Isn't it called something else now?

**Comment by chuckfernald** [comment]
Modified references to "The Conejo Valley Unitarian Universalist Fellowship" to just "Chalice".

**Comment by chuckfernald** [comment]
Fixed link to Sam, changed to:
<a href="https://www.chaliceuu.org/staff/?uid=director-religious-education">Samantha Dickerson, Director of Religious Education</a>

**Comment by chuckfernald** [comment]
Changed some subtitles that were ALL CAPS to Proper Case.
