### ISSUE TITLE
Church Library links

### ISSUE THREAD

**Issue by shaneniebergall** [cvuuf/church#67]
https://www.chaliceuu.org/learning/church-library/

"EXPLORE OUR BOOK CATALOG
EXPLORE OUR AUDIO CATALOG
FIND RECENT ADDITIONS TO THE COLLECTION"

All point to the members site so are all CVUUF centered, why are they ALL CAPS?

**Comment by GrumpyOldTroll** [comment]
Forked the legacy site portion of this to a new issue:
https://github.com/CVUUFellowship/church/issues/85

This is now just about the content of the page itself.  Links are correct, but should hopefully be moved at some point to a new system.

**Comment by shaneniebergall** [comment]
I fixed the all-caps and moved to a list instead of an offset paragraph.

![image](https://user-images.githubusercontent.com/59004683/73717767-8d3d4980-46cf-11ea-8aa7-c6630829dfe2.png)

However the other issue here is that they point to the members site and the members site has a header of CVUUF. @GrumpyOldTroll , who could we get to update this image: https://members.cvuuf.org/media/graphics/theme/public/cvuuf_title_home.png ?

**Comment by shaneniebergall** [comment]
Not worth updating old CVUUF images
