### ISSUE TITLE
Owl link to Sam needs correcting

### ISSUE THREAD

**Issue by shaneniebergall** [cvuuf/church#68]
https://www.chaliceuu.org/learning/owl-our-whole-lives-sexuality-education/

"Samantha Dickerson, Director of Religious Education, can provide information on current schedule of workshops."
Another link to Sam that goes to home

**Comment by chuckfernald** [comment]
I fixed one of these links by putting in the URL below, using the "Text" tab in Edit page.
<a href="https://www.chaliceuu.org/staff/?uid=director-religious-education">Samantha Dickerson, Director of Religious Education</a>

See left sidebar "Staff", navigate to Samantha Dickerson, and see "Staff Member URL" to find the correct link.

**Comment by kellyniebergall** [comment]
I updated the link to Sam's info
