### ISSUE TITLE
Justice Ministry updates

### ISSUE THREAD

**Issue by shaneniebergall** [cvuuf/church#69]
https://www.chaliceuu.org/justice/justice-ministry/

"Grounded in Unitarian Universalist faith and values, the CVUUF Justice Ministry offers congregants:"

ways to learn more about vital issues of the day and serve others;
active relationship with Unitarian Universalist initiatives, interfaith coalitions, movements or groups led by members of an impacted community, and legislative advocacy;
actions of witness or protest.
ECONOMIC INEQUALITY
GENDER EQUALITY & REPRODUCTIVE HEALTH
RACIAL & CULTURAL JUSTICE
The links being ALL CAPS could be cleaned up.

**Comment by kellyniebergall** [comment]
ALL CAPS have been cleaned up.
