### ISSUE TITLE
Economic Inequality updates

### ISSUE THREAD

**Issue by shaneniebergall** [cvuuf/church#70]
https://www.chaliceuu.org/justice/justice-ministry/economic-inequality/

"meets at 7pm on the last Monday of every month in Fellowship Hall"
I think they meet on the first Monday now.

"Michael Teasdale, member of the Conejo Valley Unitarian Universalist Fellowship, is the current leader of this group." should be Chalice

" Michael also co-chairs the Unitarian Universalists for a Just Economic Community."
Is Michael still chairing this group?

**Comment by kellyniebergall** [comment]
-I don't see where it mentions Michael Teasdale. New text had previously been added: Economic justice discussion groups are not currently active. We are hoping a new group will form and we encourage Chalice members to get involved. This community needs our active advocacy for fairer wages, and relief from hunger and homelessness.
-I made any updates to say Chalice
