### ISSUE TITLE
Donate updates - 2 pages??

### ISSUE THREAD

**Issue by shaneniebergall** [cvuuf/church#74]
We have 2 donate pages, why?

https://www.chaliceuu.org/giving/donate/
https://www.chaliceuu.org/donate/

The first doesn't have a sidebar. The second has 2 references that must be updated to Chalice.

**Comment by GrumpyOldTroll** [comment]
* Moved the /donate/ page to trash
 * added redirect to .htaccess:

    ~~~
    Redirect /donate/ /giving/donate/
    ~~~

 * Changed CVUUF to Chalice on /giving/donate/ page
 * Edited Paypal button to say "Donate to Chalice" instead of CVUUF.
