### ISSUE TITLE
Stewardship updates

### ISSUE THREAD

**Issue by shaneniebergall** [cvuuf/church#75]
https://www.chaliceuu.org/giving/annual-giving-your-pledge/stewardship/

"THE COMMON GOOD OF THE CONEJO VALLEY UNITARIAN UNIVERSALIST FELLOWSHIP" -> Chalice

Also, why is this in CAPS?

**Comment by GrumpyOldTroll** [comment]
Ask Don Cooper for new copy?

**Comment by GrumpyOldTroll** [comment]
Sent an email to Don.  "Do you still want this page up?  If so, could I get you to give me some new copy for it?  Thanks etc.".  I'll give it a week or so and check back pending response.

**Comment by GrumpyOldTroll** [comment]
Don responded. Took out the years so it won't look out of date when not updated, and changed the caps.
