### ISSUE TITLE
Giving FAQ updates

### ISSUE THREAD

**Issue by shaneniebergall** [cvuuf/church#76]
https://www.chaliceuu.org/giving/annual-giving-your-pledge/faqs/

"Can I change my pledge?
Yes. Fill out another pledge card and return it in at the office, or go to Make Pledge Online. You can always ask the congregational administrator or the stewardship team for help."
The Make Pledge Online link points to http://www.uuprinceton.org/about-giving/forms/ which has a slew of useful forms and might even be happy to take money intended for us, but this is NOT GOOD. 

"What is the congregational year?
Our congregational pledge year begins on October 1 and ends on September 30 of the following calendar year."
Is this correct? 

"Check(s).  Write a check made out to CVUUF and either"
to Chalice

"Credit Card. There are 2 options
Set up your own pledge and credit card or e-check payments using our online giving portal. Once logged into the portal, choose the fund: OCT 2017-SEPT 2018 Pledge."
<No Link to online giving portal on this page or on site that I see.>

"Automatic transfers from your bank.  Ask the office to set up automatic withdrawal from your bank account. Complete an Electronic Funds Transfer Authorization Form and send it to the office administrator."
No sign of this form

The word pledge is on this page 44 times. I think there are points where other substitutes would work better. 
There are many references to: Ask the office, send it to the office administrator (no link), Mail the check to the congregational office,  contacting the church office, contact the office administrator, Contact our congregational administrator for help.

**Comment by GrumpyOldTroll** [comment]
Please write to Peter Schlauss and ask him to review, also.

**Comment by kellyniebergall** [comment]
Emailed with Don Cooper, who sent corrections. Updates have been made.
