### ISSUE TITLE
Archives appears twice on sidebar

### ISSUE THREAD

**Issue by GrumpyOldTroll** [cvuuf/church#78]
Jill reported that the "Archives" list appears twice on the sidebar on "the social justice page".  I think she means this:

https://www.chaliceuu.org/justice/

It does indeed appear twice:

![image](https://user-images.githubusercontent.com/361578/72489949-96bb4c00-37ca-11ea-9c1e-a769f715532a.png)

(scrolling down)

![image](https://user-images.githubusercontent.com/361578/72489971-ac307600-37ca-11ea-8e93-5d2a15b8d30b.png)

This seems to be true on other pages as well, presumably part of the template.

**Comment by shaneniebergall** [comment]
Looks like Archives is listed twice in the sidebar config:

![image](https://user-images.githubusercontent.com/59004683/72698620-caafad80-3af9-11ea-9d3e-be91457ef74a.png)

I removed the duplicate reference.
