### ISSUE TITLE
Change calendar to use google calendar instead

### ISSUE THREAD

**Issue by GrumpyOldTroll** [cvuuf/church#8]

**Comment by GrumpyOldTroll** [comment]
As an interim solution, Rev. Anne suggested that we move to a single approver (Jessica) to check for conflicts before approving.

**Comment by brianpletcher** [comment]
Great, except Jessica isn't approving things....

**Comment by GrumpyOldTroll** [comment]
The biggest thing is conflict-detection. I think with a google calendar-like ui where you schedule something in a room, the conflicts should be a little easier to notice, and it might be possible for the room to auto-mark events as accepted on a first-come basis or something.

Rev. Anne would like to move away from the approval model. I think it would be fine as long as a) you need some level of approval in order to request a room (membership means you have it unless revoked, probably), and b) a warning that you'll lose access if you reserve it for inappropriate things, and c) an explanation of appropriate vs. not. (Including who to ask for when it's not clear.)

Mostly move away from a pre-approval model and toward a trust-but-verify model for controlling room reservation usage.

PS: If we can find or commission a wordpress plugin that can handle calendar with room reservation in some sane way, that might be even better.

PPS: IMO this isn't broken enough to try to fix urgently (or maybe I should say it's not in our worst 3 problems right now), but there are some unfortunate and awkward inconveniences with pre-approval, and I think a google-calendar-style ui has a lot of potential advantages that could make scheduling smoother, if they can be realized.

Probably a good topic for an agenda item at one of our meetings before we make any serious attempt to fix this.

**Comment by GrumpyOldTroll** [comment]
The new uua theme has an event management widget and associated calendar. It might be we can get away with using that. I'll leave this open for now, but if the integrated wordpress widget works out, we can perhaps avoid doing this work and still change calendars.

**Comment by GrumpyOldTroll** [comment]
we're not going to switch to google calendar if the current staging calendar is ok. try it out first, open a new issue else.
