### ISSUE TITLE
Climate change link in Justice Ministry

### ISSUE THREAD

**Issue by GrumpyOldTroll** [cvuuf/church#87]
A request from Jill.

![image](https://user-images.githubusercontent.com/361578/74080292-6ea0c080-49f7-11ea-82bc-45932cb41b71.png)

**Comment by chuckfernald** [comment]
I looked at this and don't understand where this sidebar is coming from.  If you fix this, let me know how.

**Comment by GrumpyOldTroll** [comment]
Hi Chuck,

The left sidebar is a menu that comes from the "Parent" that appears in the "Page Attributes" block in the classic view (but weirdly, not in the block view, which I'm going to post to a wordpress forum to ask about).  By setting the parent of the Climate Action page to the Justice Ministry page, it makes the menu contain the link, which adds it to the left sidebar.

For reference:
- Justice Ministry Page: https://www.chaliceuu.org/justice/justice-ministry/
- Climate Action Page: https://www.chaliceuu.org/justice/justice-ministry/climate-change-action/

Setting:
![image](https://user-images.githubusercontent.com/361578/74108376-79aa3c80-4b2e-11ea-9e0f-048e4da9a50e.png)

Before saving setting:
![image](https://user-images.githubusercontent.com/361578/74108382-93e41a80-4b2e-11ea-920a-5b3e41dda75f.png)

After saving setting: (note the new entry in the left sidebar):
![image](https://user-images.githubusercontent.com/361578/74108402-df96c400-4b2e-11ea-8126-ccce63027f9d.png)

After setting the "Order" field in the Climate Action page to 4:
![image](https://user-images.githubusercontent.com/361578/74108444-68adfb00-4b2f-11ea-955a-c97d2803e769.png)

As to where the left sidebar is configured when you're on the Justice Ministry page, I'm actually disturbingly unsure.  I don't think it's the "Left Sidebar" menu that can be edited in the menu stuff.  My best guess is here, in the "Appearance/Theme Editor" view, which gives you a warning not to make edits there:
![image](https://user-images.githubusercontent.com/361578/74108593-d0b11100-4b30-11ea-915f-a948d3d7eb84.png)

@shaneniebergall , I think you were looking at how this works in another ticket, right?  Maybe you found where this lives?  If so, a follow-up explaining it would be cool, if you get a chance.

Anyway, HTH, and I'll send a response to Jill and let her know this is fixed, I think.

**Comment by shaneniebergall** [comment]
@GrumpyOldTroll @chuckfernald The left menu's are handled by the Appearance -> Menu settings:

![image](https://user-images.githubusercontent.com/59004683/74211045-0c3c0000-4c43-11ea-93b9-40e47451cd00.png)
