### ISSUE TITLE
Add Anthony to the Staff page

### ISSUE THREAD

**Issue by GrumpyOldTroll** [cvuuf/church#93]
Dianna sent:
Please add  Anthony to the staff page.  

Anthony Concepcion 
Music Director 
musicdirector@chaliceuu.org 

----

We also need a picture and ideally a bio.

**Comment by shanewiredin** [comment]
Add Anthony, and replaced Dianna with Chavonne: https://www.chaliceuu.org/about-us/our-leadership/
